#!/bin/sh
cd /opt/voclipse/
# https://bugs.eclipse.org/bugs/show_bug.cgi?id=421127
export SWT_GTK3=0
# https://bugs.eclipse.org/bugs/show_bug.cgi?id=420099
export UBUNTU_MENUPROXY=0
./voclipse -Declipse.consoleLog=true -debug -showlocation
